import { Geist, Geist_Mono,Playfair_Display, Inter,Montserrat } from "next/font/google";
import "./globals.css";
import "../assets/css/styles.scss";

const inter = Inter({ subsets: ["latin"] });

import Header from "../components/header";
import ReduxProvider from "../store/provider";

import PopupProvider from "../components/loginpopup/PopupProvider";
import LayoutWrapper from "../components/LayoutWrapper";
import AuthLoader from "../components/AuthLoader";
import Footer from "../components/footer";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const montserrat = Montserrat({
  subsets: ['latin'],
  weights: ['400', '500', '600'], // specify the weights you need
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
     <body
        className={`${geistSans.variable} ${geistMono.variable} ${montserrat.className} antialiased`}
      >
        <div className="app-main">
          <ReduxProvider>
              <AuthLoader />
            <PopupProvider>
            
                <Header />


              <LayoutWrapper>
                {children}
              </LayoutWrapper>

              <Footer />
            </PopupProvider>
          </ReduxProvider>
        </div>
      </body>
    </html>
  );
}
