import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "../assets/css/styles.scss";


import Header from "../components/header";
import ReduxProvider from "../store/provider";

import PopupProvider from "../components/loginpopup/PopupProvider";


import Footer from "../components/footer";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="app-main">
          <ReduxProvider>
            <PopupProvider>
               <div className="fixed top-0 left-0 w-full z-50 bg-white shadow-sm">
                <Header />
              </div>
              <main className="pt-16">
                {children}
              </main>

              <Footer />
            </PopupProvider>
          </ReduxProvider>
        </div>
      </body>
    </html>
  );
}
